---
- hosts: monsrv 
  sudo: yes
  remote_user: vagrant

  tasks:
  - hostname: name=monsrv
  
  - service: name=iptables enabled=no
  - service: name=iptables state=stopped
  
  - name: Install wget
    yum: name=wget state=present

  - name: Add Zabbix repository
    yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present

  - name: Install Zabbix-Server
    yum: name=zabbix-server-mysql state=present

  - name: Install Zabbix-Web-Mysql
    yum: name=zabbix-web-mysql state=present

  - name: Install the Python MySQL module
    yum: name=MySQL-python

  - name: Install Mysql Server
    yum: name=mysql-server state=present

  - service: name=mysqld state=started
  - service: name=mysqld enabled=yes
  
  - name: Create zabbix database 
    mysql_db: name=zabbix state=present collation=utf8_general_ci
    register: mysql_db

  - mysql_user: name=zabbix password=zabbix priv=*.*:ALL state=present
  
  - name: Import schema sql
    mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.6/create/schema.sql
    when: mysql_db.changed

  - name: Import images sql
    mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.6/create/images.sql
    when: mysql_db.changed

  - name: Import data sql
    mysql_db: state=import name=zabbix target=/usr/share/doc/zabbix-server-mysql-2.4.6/create/data.sql
    when: mysql_db.changed

  - name: Change time zone
    command: sed -i 's/# php_value date.timezone Europe\/Riga/php_value date.timezone Europe\/Kiev/g' /etc/httpd/conf.d/zabbix.conf

  - name: Change Zabbix Server conf
    command: sed -i 's/# DBHost=localhost/DBHost=localhost/g' /etc/zabbix/zabbix_server.conf

  - name: Change Zabbix Server conf 2
    command: sed -i 's/# DBPassword=/DBPassword=zabbix/g' /etc/zabbix/zabbix_server.conf 

  - name: Install SNMPD
    yum: name=net-snmp-utils state=present
    yum: name=net-snmp state=present

  - service: name=snmpd state=restarted
  - service: name=snmpd enabled=yes
  
  - name: Install Apache HTTP
    yum: name=httpd state=latest
    yum: name=mod_ssl state=latest

  - service: name=httpd state=restarted

  - service: name=httpd enabled=yes

  - service: name=zabbix-server enabled=yes

  - service: name=zabbix-server state=restarted

  - name: Install Zabbix-Client
    yum: name=zabbix-agent state=present
  
  - service: name=zabbix-agent state=started

  - service: name=zabbix-agent enabled=yes

