- hosts: appsrv 
  sudo: yes
  remote_user: vagrant

  tasks:

  - name: copy app class
    shell: cp /vagrant/HomeWork.java /opt/

  - name: copy run script
    shell: cp /vagrant/run_app.sh /opt/

  - name: compile class 
    shell: cd /opt; javac HomeWork.java

  - name: autorun
    lineinfile: dest=/etc/rc.d/rc.local line="bash /opt/run_app.sh"

  - name: Start Java app
    shell: bash /opt/run_app.sh

#shell: cd /opt ;  nohup java HomeWork & 
#command: bash /opt/run_app.sh
    

